package entity;
// Generated May 3, 2016 2:14:50 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="bakeryapp"
)
public class Product  implements java.io.Serializable {


     private String productId;
     private String productName;
     private Double productPrice;
     private String productCategory;
     private String productDesc;
     private String image;
     private byte[] pruductImage;

    public Product() {
    }

	
    public Product(String productId) {
        this.productId = productId;
    }
    public Product(String productId, String productName, Double productPrice, String productCategory, String productDesc, String image, byte[] pruductImage) {
       this.productId = productId;
       this.productName = productName;
       this.productPrice = productPrice;
       this.productCategory = productCategory;
       this.productDesc = productDesc;
       this.image = image;
       this.pruductImage = pruductImage;
    }
    
    public Product(Product p){
        
        this.productId = p.productId;
        this.productName = p.productName;
        this.productPrice = p.productPrice;
        this.productCategory = p.productCategory;
        this.productDesc = p.productDesc;
        this.image = p.image;
        this.pruductImage = p.pruductImage;
        
    }
   
     @Id 

    
    @Column(name="productId", unique=true, nullable=false, length=15)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="productName", length=100)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="productPrice", precision=22, scale=0)
    public Double getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    
    @Column(name="productCategory", length=30)
    public String getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }

    
    @Column(name="productDesc", length=65535)
    public String getProductDesc() {
        return this.productDesc;
    }
    
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    
    @Column(name="image", length=1000)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="pruductImage")
    public byte[] getPruductImage() {
        return this.pruductImage;
    }
    
    public void setPruductImage(byte[] pruductImage) {
        this.pruductImage = pruductImage;
    }

}


